### PR TITLE
Extend action functionality

### PR DESCRIPTION
**Pull request by ironashram**
# Summary of changes

- Add support for quay.io registry
- Allow docker compose files to be anywhere in the repo

# Does it keep it simple?
YES

## Breaking Changes?
NO

## How changes have been tested?, link to your runs
https://github.com/ironashram/mail-matrix-server/pull/3
https://github.com/ironashram/mail-matrix-server/actions/runs/7685036628/job/20942251854

## Any unknowns or heads ups?
NO

### CODE REVIEW

**Comment by ironashram** [comment]
@sbe-arg this seems working fine now, have a look if you're interested

**Comment by sbe-arg** [comment]
Not sure is about working fine is about why adding an unnecessary for loop to the logic.

Happy with the quay support part.

**Comment by ironashram** [comment]
> Not sure is about working fine is about why adding an unnecessary for loop to the logic.
> 
> Happy with the quay support part.

removed the unnecessary loop while keeping the ability to have compose files anywhere

let me know if something else needs to be revised

**Comment by sbe-arg** [comment]
@ironashram the last thing is if you can bump the VERSION file to v1.1.0 so we can auto release the action

Thanks for sorting the whitespace.

**Comment by ironashram** [comment]
> @ironashram the last thing is if you can bump the VERSION file to v1.1.0 so we can auto release the action
> 
> Thanks for sorting the whitespace.

ok i did bump the version file, also fixed an issue with some quay images by increasing the pagination limit

**Comment by sbe-arg** [comment]
Awesome thanks, Ill merge soon.

**Review by sbe-arg — APPROVED** [review]

**Pull request merged**
